### ISSUE TITLE
Quickwit index mapping config

### ISSUE THREAD

**Issue by tuziben** [tuziben/quickwit#2]
Github archive data set

```yaml
version: 0.6

index_id: gh-archive

doc_mapping:
  field_mappings:
    - name: id
      type: text
      tokenizer: raw
    - name: type
      type: text
      fast: true
      tokenizer: raw
    - name: public
      type: bool
      fast: true
    - name: payload
      type: object
      field_mappings:
        - name: pull_request
          type: object
          field_mappings:
            - name: body
              type: text
              tokenizer: default
              record: position
    - name: org
      type: json
      tokenizer: default
    - name: repo
      type: json
      tokenizer: default
    - name: actor
      type: json
      tokenizer: default
    - name: other
      type: json
      tokenizer: default
    - name: created_at
      type: datetime
      fast: true
      input_formats:
        - rfc3339
      fast_precision: seconds
  timestamp_field: created_at

indexing_settings:
  commit_timeout_secs: 10
```
