### ISSUE TITLE
quickwit query 模式

### ISSUE THREAD

**Issue by tuziben** [tuziben/quickwit#6]
```
doc_mapping:
  store_source: false
  timestamp_field: timestamp
  mode: dynamic
  field_mappings:
    - name: timestamp
      type: datetime
      input_formats:
        - iso8601
      output_format: rfc3339
      stored: true
      indexed: true
      fast: true
      precision: milliseconds

    - name: request_url
      type: text
      tokenizer: default

    - name: request_url_fast
      type: text

    - name: request_url_position
      type: text
      tokenizer: default
      record: position

    - name: redirect_url_position_fast
      type: text
      tokenizer: default
      record: position
      fast: true
```
